// Dummy OpenFeedback Provider for the Demo App
// In a real app, this leverages session state or context. For the demo, we generate it dynamically.
"use client";

import { useMemo } from "react";
import { OpenFeedbackProvider as SDKProvider } from "@openfeedback/react";

// The demo uses a public Supabase URL and Anon Key defined in the environment
const API_URL = process.env.NEXT_PUBLIC_SUPABASE_URL || "http://127.0.0.1:54321/functions/v1";
const PROJECT_ID = process.env.NEXT_PUBLIC_OPENFEEDBACK_PROJECT_ID || "proj_local_123";

/**
 * OpenFeedbackClientWrapper
 *
 * In OpenFeedback's Signed Stateless Auth model, the frontend doesn't need to know who
 * the user is — it just needs the auth context (the user's ID, a fresh timestamp, and
 * the cryptographic signature generated by the Server Action) to pass it to the API.
 */
export function OpenFeedbackClientWrapper({
    children,
    authContext
}: {
    children: React.ReactNode;
    authContext: any;
}) {
    const config = useMemo(() => ({
        projectId: PROJECT_ID,
        apiUrl: API_URL,
    }), []);

    return (
        <SDKProvider
            config={config}
            anonKey="demo-anon-key"
            authContext={authContext}
        >
            {children}
        </SDKProvider>
    );
}
